[package]
name = "projct-core"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3"
regex = "1.0"
walkdir = "2.5"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0", features = ["derive"] }